Lint/AssignmentInCondition:
  Exclude:
    - 'bin/spring'

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'
    - 'app/controllers/*'
    - 'app/helpers/application_helper.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  Exclude:
    - 'db/**/*'
